In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('reviews_dataset.csv')

In [4]:
df.head()

,id,text,sentiment,text_type
0,1,<p>OMG!!! I recieved this phone yestarday and ...,negative,product_review
1,2,<div>Absolutely LOVE this product!!! 😍😍</div> ...,positive,product_review
2,3,<p>Worst restaurant experience ever!!!</p> We ...,negative,restaurant_review
3,4,OMG this movie was sooo good!!! 🎬❤️ I watched ...,positive,movie_review
4,5,<h2>Terrible application update</h2> This app ...,negative,app_review

In [5]:
df['text'][0]

"<p>OMG!!! I recieved this phone yestarday and I'm sooo disapointed 😭😭</p> The packaging looked nice but the phone stopped working after only two days. I tried restarting it several times and followed the instructions on the website, but nothing helped. The customer service team was not helpful at all because they kept sending the same automated reply instead of solving my problem. tbh I expected much better quality for this price!!! More details: https://example.com/review #badexperience @support"

# Lowercasing

In [6]:
df['text'] = df['text'].str.lower()

In [7]:
df

,id,text,sentiment,text_type
0,1,<p>omg!!! i recieved this phone yestarday and ...,negative,product_review
1,2,<div>absolutely love this product!!! 😍😍</div> ...,positive,product_review
2,3,<p>worst restaurant experience ever!!!</p> we ...,negative,restaurant_review
3,4,omg this movie was sooo good!!! 🎬❤️ i watched ...,positive,movie_review
4,5,<h2>terrible application update</h2> this app ...,negative,app_review
5,6,i luv this skincare product sooo much!!! 😊✨ i ...,positive,product_review
6,7,<p>my online order was a complete mess!!!</p> ...,negative,service_review
7,8,the hotel was pretty good overall 😊🏨 we stayed...,positive,hotel_review
8,9,this laptop is okay but not as amazing as the ...,neutral,product_review
9,10,<div>customer support needs serious improvemen...,negative,service_review

# Remove HTML Tags

In [8]:
import re
def remove_html_tags(text):
    pattern = re.compile('<.*?>')
    return pattern.sub(r'',text)

In [9]:
df['text'] = df['text'].apply(remove_html_tags)

# Remove URLs

In [10]:
def remove_url(text):
    pattern = re.compile(r'https?://\S+|www\.\S+')
    return pattern.sub(r'',text)

In [11]:
df['text'] = df['text'].apply(remove_url)

# Removing Punctuation

In [12]:
import string,time
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [13]:
exclude = string.punctuation

In [14]:
def remove_punc(text):
    for char in exclude:
        text = text.replace(char,'')
    return text

In [15]:
df['text'] = df['text'].apply(remove_punc)

In [16]:
df

,id,text,sentiment,text_type
0,1,omg i recieved this phone yestarday and im soo...,negative,product_review
1,2,absolutely love this product 😍😍 i ordered thes...,positive,product_review
2,3,worst restaurant experience ever we visited th...,negative,restaurant_review
3,4,omg this movie was sooo good 🎬❤️ i watched it ...,positive,movie_review
4,5,terrible application update this app keeps cra...,negative,app_review
5,6,i luv this skincare product sooo much 😊✨ i hav...,positive,product_review
6,7,my online order was a complete mess i ordered ...,negative,service_review
7,8,the hotel was pretty good overall 😊🏨 we stayed...,positive,hotel_review
8,9,this laptop is okay but not as amazing as the ...,neutral,product_review
9,10,customer support needs serious improvement i h...,negative,service_review

# Chat word Treatment

In [17]:
chat_words = {
    "u": "you",
    "r": "are",
    "ur": "your",
    "gr8": "great",
    "b4": "before",
    "l8r": "later",
    "btw": "by the way",
    "idk": "I do not know",
    "imo": "in my opinion",
    "omg": "oh my god",
    "lol": "laughing out loud",
    "brb": "be right back",
    "ttyl": "talk to you later",
    "thx": "thanks",
    "thnx": "thanks",
    "pls": "please",
    "plz": "please",
    "asap": "as soon as possible",
    "rn": "right now",
    "bc": "because",
    "cuz": "because",
    "msg": "message",
    "ppl": "people",
    "dm": "direct message",
    "tbh": "to be honest",
    "smh": "shaking my head",
    "tysm": "thank you so much",
    "np": "no problem",
    "omw": "on my way",
    "wanna": "want to",
    "gonna": "going to",
    "luv": "love",
    "k": "okay",
    "bff": "best friend forever"
}

def chat_conversion(text):
    new_text = []

    for word in text.split():
        clean_word = word.lower().strip(".,!?;:")

        if clean_word in chat_words:
            new_text.append(chat_words[clean_word])
        else:
            new_text.append(word)

    return " ".join(new_text)

In [18]:
text = "OMG!!! u r gr8. Plz msg me ASAP, brb rn lol."

print(chat_conversion(text))

oh my god you are great please message me as soon as possible be right back right now laughing out loud

# Spelling Correction

In [19]:
%pip install textblob

Requirement already satisfied: textblob in C:\Users\Anushka\anaconda3\Lib\site-packages (0.20.1)
Requirement already satisfied: nltk>=3.9 in C:\Users\Anushka\anaconda3\Lib\site-packages (from textblob) (3.9.2)
Requirement already satisfied: click in C:\Users\Anushka\anaconda3\Lib\site-packages (from nltk>=3.9->textblob) (8.2.1)
Requirement already satisfied: joblib in C:\Users\Anushka\anaconda3\Lib\site-packages (from nltk>=3.9->textblob) (1.4.2)
Requirement already satisfied: regex>=2021.8.3 in C:\Users\Anushka\anaconda3\Lib\site-packages (from nltk>=3.9->textblob) (2026.5.9)
Requirement already satisfied: tqdm in C:\Users\Anushka\anaconda3\Lib\site-packages (from nltk>=3.9->textblob) (4.67.1)
Requirement already satisfied: colorama in C:\Users\Anushka\anaconda3\Lib\site-packages (from click->nltk>=3.9->textblob) (0.4.6)
Note: you may need to restart the kernel to use updated packages.

WARNING: Ignoring invalid distribution ~atplotlib (C:\Users\Anushka\anaconda3\Lib\site-packages)
WARNING: Ignoring invalid distribution ~atplotlib (C:\Users\Anushka\anaconda3\Lib\site-packages)
WARNING: Ignoring invalid distribution ~atplotlib (C:\Users\Anushka\anaconda3\Lib\site-packages)

In [20]:
from textblob import TextBlob

def correct_spelling(text):
    blob = TextBlob(text)
    return str(blob.correct())

In [21]:
text = "I recieved teh prodcut yestarday and it was awsome."

corrected_text = correct_spelling(text)

print("Original:", text)
print("Corrected:", corrected_text)

Original: I recieved teh prodcut yestarday and it was awsome.
Corrected: I received the product yesterday and it was some.

# Removing Stopwords

In [22]:
from nltk.corpus import stopwords

In [23]:
stop_words = set(stopwords.words('english'))

In [24]:
def remove_stopwords(text):
    words = text.split()
    filtered_words = []

    for word in words:
        if word.lower() not in stop_words:
            filtered_words.append(word)

    return " ".join(filtered_words)

In [25]:
text = "This product is very good and I am happy with the quality."

print("Original:", text)
print("After stopword removal:", remove_stopwords(text))

Original: This product is very good and I am happy with the quality.
After stopword removal: product good happy quality.

# Handling Emojis

In [26]:
%pip install emoji

Requirement already satisfied: emoji in C:\Users\Anushka\anaconda3\Lib\site-packages (2.16.0)
Note: you may need to restart the kernel to use updated packages.

WARNING: Ignoring invalid distribution ~atplotlib (C:\Users\Anushka\anaconda3\Lib\site-packages)
WARNING: Ignoring invalid distribution ~atplotlib (C:\Users\Anushka\anaconda3\Lib\site-packages)
WARNING: Ignoring invalid distribution ~atplotlib (C:\Users\Anushka\anaconda3\Lib\site-packages)

In [27]:
import emoji

In [28]:
text = "This product is amazing 😍😊! I love it ❤️"

processed_text = emoji.demojize(text)

print("Original:", text)
print("Processed:", processed_text)

Original: This product is amazing 😍😊! I love it ❤️
Processed: This product is amazing :smiling_face_with_heart-eyes::smiling_face_with_smiling_eyes:! I love it :red_heart:

In [29]:
text = "The product is amazing 😍😊! I love it ❤️"

processed_text = emoji.replace_emoji(text, replace="")

print("Original:", text)
print("After removing emojis:", processed_text)

Original: The product is amazing 😍😊! I love it ❤️
After removing emojis: The product is amazing ! I love it

In [30]:
df["emoji_processed"] = df["text"].apply(
    lambda text: emoji.demojize(str(text))
)

df[["text", "emoji_processed"]].head()

,text,emoji_processed
0,omg i recieved this phone yestarday and im soo...,omg i recieved this phone yestarday and im soo...
1,absolutely love this product 😍😍 i ordered thes...,absolutely love this product :smiling_face_wit...
2,worst restaurant experience ever we visited th...,worst restaurant experience ever we visited th...
3,omg this movie was sooo good 🎬❤️ i watched it ...,omg this movie was sooo good :clapper_board::r...
4,terrible application update this app keeps cra...,terrible application update this app keeps cra...

# Tokenization  -  is the process of splitting a piece of text into smaller units called tokens. These tokens can be words, sentences, or subwords.

## Using the split function

In [31]:
# word tokenization
sent1 = "I am going to Delhi"
sent1.split()

['I', 'am', 'going', 'to', 'Delhi']

In [33]:
# sentance tokenization
sent2 = "I am going to Delhi. I will stay there for 2 days. I would love to visit India Gate"
sent2.split('.')

['I am going to Delhi',
 ' I will stay there for 2 days',
 ' I would love to visit India Gate']

### Problems with the split() function

Punctuation remains attached to words, such as "Hello," and "amazing."

Multiple spaces are handled correctly by default, but the original spacing information is lost.

Contractions such as "don't" and "I've" are not split into meaningful components.

Punctuation, combined emojis, and hashtags remain grouped together.

## Using Regex

In [34]:
text = "This phone costs 15000 rupees."

text = re.sub(r'\d+', '', text)
print(text)

This phone costs  rupees.

## NLTK

In [35]:
%pip install nltk

Requirement already satisfied: nltk in C:\Users\Anushka\anaconda3\Lib\site-packages (3.9.2)
Requirement already satisfied: click in C:\Users\Anushka\anaconda3\Lib\site-packages (from nltk) (8.2.1)
Requirement already satisfied: joblib in C:\Users\Anushka\anaconda3\Lib\site-packages (from nltk) (1.4.2)
Requirement already satisfied: regex>=2021.8.3 in C:\Users\Anushka\anaconda3\Lib\site-packages (from nltk) (2026.5.9)
Requirement already satisfied: tqdm in C:\Users\Anushka\anaconda3\Lib\site-packages (from nltk) (4.67.1)
Requirement already satisfied: colorama in C:\Users\Anushka\anaconda3\Lib\site-packages (from click->nltk) (0.4.6)
Note: you may need to restart the kernel to use updated packages.

WARNING: Ignoring invalid distribution ~atplotlib (C:\Users\Anushka\anaconda3\Lib\site-packages)
WARNING: Ignoring invalid distribution ~atplotlib (C:\Users\Anushka\anaconda3\Lib\site-packages)
WARNING: Ignoring invalid distribution ~atplotlib (C:\Users\Anushka\anaconda3\Lib\site-packages)

In [36]:
import nltk

In [37]:
# word tokenize
from nltk.tokenize import word_tokenize
text = "NLTK is useful for Natural Language Processing!"

tokens = word_tokenize(text)

print(tokens)

['NLTK', 'is', 'useful', 'for', 'Natural', 'Language', 'Processing', '!']

In [38]:
# sentence tokenize
from nltk.tokenize import sent_tokenize

text = "I am learning NLP. NLTK makes text processing easier."

sentences = sent_tokenize(text)

print(sentences)

['I am learning NLP.', 'NLTK makes text processing easier.']

# Spacy

In [39]:
%pip install spacy

Requirement already satisfied: spacy in C:\Users\Anushka\anaconda3\Lib\site-packages (3.8.14)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in C:\Users\Anushka\anaconda3\Lib\site-packages (from spacy) (3.0.12)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in C:\Users\Anushka\anaconda3\Lib\site-packages (from spacy) (1.0.5)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in C:\Users\Anushka\anaconda3\Lib\site-packages (from spacy) (1.0.15)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in C:\Users\Anushka\anaconda3\Lib\site-packages (from spacy) (2.0.13)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in C:\Users\Anushka\anaconda3\Lib\site-packages (from spacy) (3.0.13)
Requirement already satisfied: thinc<8.4.0,>=8.3.12 in C:\Users\Anushka\anaconda3\Lib\site-packages (from spacy) (8.3.13)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in C:\Users\Anushka\anaconda3\Lib\site-packages (from spacy) (1.1.3)
Requirement already satisfied: srsly<3.0.0,>=2.5.3 in C:\Users\Anushka\anaconda3\Lib\site-packages (from spacy) (2.5.3)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in C:\Users\Anushka\anaconda3\Lib\site-packages (from spacy) (2.0.10)
Requirement already satisfied: weasel<2.0.0,>=1.0.0 in C:\Users\Anushka\anaconda3\Lib\site-packages (from spacy) (1.0.0)
Requirement already satisfied: confection<2.0.0,>=1.3.2 in C:\Users\Anushka\anaconda3\Lib\site-packages (from spacy) (1.3.3)
Requirement already satisfied: typer<1.0.0,>=0.3.0 in C:\Users\Anushka\anaconda3\Lib\site-packages (from spacy) (0.20.0)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in C:\Users\Anushka\anaconda3\Lib\site-packages (from spacy) (4.67.1)
Requirement already satisfied: numpy>=1.19.0 in C:\Users\Anushka\anaconda3\Lib\site-packages (from spacy) (2.3.5)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in C:\Users\Anushka\anaconda3\Lib\site-packages (from spacy) (2.32.5)
Requirement already satisfied: pydantic<3.0.0,>=2.0.0 in C:\Users\Anushka\anaconda3\Lib\site-packages (from spacy) (2.10.4)
Requirement already satisfied: jinja2 in C:\Users\Anushka\anaconda3\Lib\site-packages (from spacy) (3.1.6)
Requirement already satisfied: setuptools in C:\Users\Anushka\anaconda3\Lib\site-packages (from spacy) (80.9.0)
Requirement already satisfied: packaging>=20.0 in C:\Users\Anushka\anaconda3\Lib\site-packages (from spacy) (24.2)
Requirement already satisfied: annotated-types>=0.6.0 in C:\Users\Anushka\anaconda3\Lib\site-packages (from pydantic<3.0.0,>=2.0.0->spacy) (0.6.0)
Requirement already satisfied: pydantic-core==2.27.2 in C:\Users\Anushka\anaconda3\Lib\site-packages (from pydantic<3.0.0,>=2.0.0->spacy) (2.27.2)
Requirement already satisfied: typing-extensions>=4.12.2 in C:\Users\Anushka\anaconda3\Lib\site-packages (from pydantic<3.0.0,>=2.0.0->spacy) (4.15.0)
Requirement already satisfied: charset_normalizer<4,>=2 in C:\Users\Anushka\anaconda3\Lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in C:\Users\Anushka\anaconda3\Lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in C:\Users\Anushka\anaconda3\Lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in C:\Users\Anushka\anaconda3\Lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (2026.1.4)
Requirement already satisfied: blis<1.4.0,>=1.3.0 in C:\Users\Anushka\anaconda3\Lib\site-packages (from thinc<8.4.0,>=8.3.12->spacy) (1.3.3)
Requirement already satisfied: colorama in C:\Users\Anushka\anaconda3\Lib\site-packages (from tqdm<5.0.0,>=4.38.0->spacy) (0.4.6)
Requirement already satisfied: click>=8.0.0 in C:\Users\Anushka\anaconda3\Lib\site-packages (from typer<1.0.0,>=0.3.0->spacy) (8.2.1)
Requirement already satisfied: shellingham>=1.3.0 in C:\Users\Anushka\anaconda3\Lib\site-packages (from typer<1.0.0,>=0.3.0->spacy) (1.5.4)
Requirement already satisfied: rich>=10.11.0 in C:\Users\Anushka\anaconda3\Lib\site-packages (from typer<1.0.0,>=0.3.0->spacy) (14.2.0)
Requirement already satisfied: cloudpathlib>=0.7.0 in C:\Users\Anushka\anaconda3\Lib\site-packages (from weasel<2.0.0,>=1.0.0->spacy) (0.24.0)
Requirement already satisfied: smart-open>=5.2.1 in C:\Users\Anushka\anaconda3\Lib\site-packages (from weasel<2.0.0,>=1.0.0->spacy) (7.6.1)
Requirement already satisfied: httpx>=0.24.0 in C:\Users\Anushka\anaconda3\Lib\site-packages (from weasel<2.0.0,>=1.0.0->spacy) (0.28.1)
Requirement already satisfied: anyio in C:\Users\Anushka\anaconda3\Lib\site-packages (from httpx>=0.24.0->weasel<2.0.0,>=1.0.0->spacy) (4.10.0)
Requirement already satisfied: httpcore==1.* in C:\Users\Anushka\anaconda3\Lib\site-packages (from httpx>=0.24.0->weasel<2.0.0,>=1.0.0->spacy) (1.0.9)
Requirement already satisfied: h11>=0.16 in C:\Users\Anushka\anaconda3\Lib\site-packages (from httpcore==1.*->httpx>=0.24.0->weasel<2.0.0,>=1.0.0->spacy) (0.16.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in C:\Users\Anushka\anaconda3\Lib\site-packages (from rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in C:\Users\Anushka\anaconda3\Lib\site-packages (from rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in C:\Users\Anushka\anaconda3\Lib\site-packages (from markdown-it-py>=2.2.0->rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy) (0.1.2)
Requirement already satisfied: wrapt in C:\Users\Anushka\anaconda3\Lib\site-packages (from smart-open>=5.2.1->weasel<2.0.0,>=1.0.0->spacy) (2.2.2)
Requirement already satisfied: sniffio>=1.1 in C:\Users\Anushka\anaconda3\Lib\site-packages (from anyio->httpx>=0.24.0->weasel<2.0.0,>=1.0.0->spacy) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in C:\Users\Anushka\anaconda3\Lib\site-packages (from jinja2->spacy) (3.0.2)
Note: you may need to restart the kernel to use updated packages.

WARNING: Ignoring invalid distribution ~atplotlib (C:\Users\Anushka\anaconda3\Lib\site-packages)
WARNING: Ignoring invalid distribution ~atplotlib (C:\Users\Anushka\anaconda3\Lib\site-packages)
WARNING: Ignoring invalid distribution ~atplotlib (C:\Users\Anushka\anaconda3\Lib\site-packages)

In [40]:
!python -m spacy download en_core_web_sm

Collecting en-core-web-sm==3.8.0
  Downloading en_core_web_sm-3.8.0-py3-none-any.whl (12.8 MB)
     ---------------------------------------- 0.0/12.8 MB ? eta -:--:--
      --------------------------------------- 0.3/12.8 MB ? eta -:--:--
     --- ------------------------------------ 1.0/12.8 MB 5.2 MB/s eta 0:00:03
     ----- ---------------------------------- 1.8/12.8 MB 3.7 MB/s eta 0:00:03
     ------- -------------------------------- 2.4/12.8 MB 3.6 MB/s eta 0:00:03
     --------- ------------------------------ 2.9/12.8 MB 3.4 MB/s eta 0:00:03
     ---------- ----------------------------- 3.4/12.8 MB 3.2 MB/s eta 0:00:03
     ----------- ---------------------------- 3.7/12.8 MB 2.9 MB/s eta 0:00:04
     ----------- ---------------------------- 3.7/12.8 MB 2.9 MB/s eta 0:00:04
     ------------ --------------------------- 3.9/12.8 MB 2.4 MB/s eta 0:00:04
     ------------ --------------------------- 3.9/12.8 MB 2.4 MB/s eta 0:00:04
     ------------ --------------------------- 3.9/12.8 MB 2.4 MB/s eta 0:00:04
     ------------ --------------------------- 3.9/12.8 MB 2.4 MB/s eta 0:00:04
     ------------- -------------------------- 4.2/12.8 MB 1.7 MB/s eta 0:00:06
     ------------- -------------------------- 4.5/12.8 MB 1.6 MB/s eta 0:00:06
     ------------- -------------------------- 4.5/12.8 MB 1.6 MB/s eta 0:00:06
     -------------- ------------------------- 4.7/12.8 MB 1.5 MB/s eta 0:00:06
     --------------- ------------------------ 5.0/12.8 MB 1.4 MB/s eta 0:00:06
     --------------- ------------------------ 5.0/12.8 MB 1.4 MB/s eta 0:00:06
     ---------------- ----------------------- 5.2/12.8 MB 1.4 MB/s eta 0:00:06
     ---------------- ----------------------- 5.2/12.8 MB 1.4 MB/s eta 0:00:06
     ----------------- ---------------------- 5.5/12.8 MB 1.3 MB/s eta 0:00:06
     ------------------ --------------------- 5.8/12.8 MB 1.3 MB/s eta 0:00:06
     ------------------ --------------------- 6.0/12.8 MB 1.3 MB/s eta 0:00:06
     ------------------ --------------------- 6.0/12.8 MB 1.3 MB/s eta 0:00:06
     ------------------- -------------------- 6.3/12.8 MB 1.2 MB/s eta 0:00:06
     -------------------- ------------------- 6.6/12.8 MB 1.2 MB/s eta 0:00:06
     --------------------- ------------------ 6.8/12.8 MB 1.2 MB/s eta 0:00:05
     ---------------------- ----------------- 7.1/12.8 MB 1.2 MB/s eta 0:00:05
     ----------------------- ---------------- 7.6/12.8 MB 1.3 MB/s eta 0:00:05
     ------------------------ --------------- 7.9/12.8 MB 1.3 MB/s eta 0:00:04
     ------------------------- -------------- 8.1/12.8 MB 1.3 MB/s eta 0:00:04
     -------------------------- ------------- 8.4/12.8 MB 1.3 MB/s eta 0:00:04
     --------------------------- ------------ 8.7/12.8 MB 1.3 MB/s eta 0:00:04
     ---------------------------- ----------- 9.2/12.8 MB 1.3 MB/s eta 0:00:03
     ----------------------------- ---------- 9.4/12.8 MB 1.3 MB/s eta 0:00:03
     ----------------------------- ---------- 9.4/12.8 MB 1.3 MB/s eta 0:00:03
     ------------------------------ --------- 9.7/12.8 MB 1.3 MB/s eta 0:00:03
     ------------------------------- -------- 10.0/12.8 MB 1.3 MB/s eta 0:00:03
     ------------------------------- -------- 10.2/12.8 MB 1.3 MB/s eta 0:00:03
     ------------------------------- -------- 10.2/12.8 MB 1.3 MB/s eta 0:00:03
     -------------------------------- ------- 10.5/12.8 MB 1.3 MB/s eta 0:00:02
     --------------------------------- ------ 10.7/12.8 MB 1.2 MB/s eta 0:00:02
     --------------------------------- ------ 10.7/12.8 MB 1.2 MB/s eta 0:00:02
     --------------------------------- ------ 10.7/12.8 MB 1.2 MB/s eta 0:00:02
     ---------------------------------- ----- 11.0/12.8 MB 1.2 MB/s eta 0:00:02
     ----------------------------------- ---- 11.3/12.8 MB 1.2 MB/s eta 0:00:02
     ----------------------------------- ---- 11.3/12.8 MB 1.2 MB/s eta 0:00:02
     ------------------------------------ --- 11.5/12.8 MB 1.2 MB/s eta 0:00:02
     ------------------------------------ --- 11.8/12.8 MB 1.2 MB/s eta 0:00:01
     ------------------------------------- -- 12.1/12.8 MB 1.2 MB/s eta 0:00:01
     -------------------------------------- - 12.3/12.8 MB 1.2 MB/s eta 0:00:01
     -------------------------------------- - 12.3/12.8 MB 1.2 MB/s eta 0:00:01
     -------------------------------------- - 12.3/12.8 MB 1.2 MB/s eta 0:00:01
     ---------------------------------------  12.6/12.8 MB 1.1 MB/s eta 0:00:01
     ---------------------------------------  12.6/12.8 MB 1.1 MB/s eta 0:00:01
     ---------------------------------------  12.6/12.8 MB 1.1 MB/s eta 0:00:01
     ---------------------------------------- 12.8/12.8 MB 1.1 MB/s  0:00:11
[+] Download and installation successful
You can now load the package via spacy.load('en_core_web_sm')

WARNING: Ignoring invalid distribution ~atplotlib (C:\Users\Anushka\anaconda3\Lib\site-packages)
WARNING: Ignoring invalid distribution ~atplotlib (C:\Users\Anushka\anaconda3\Lib\site-packages)
WARNING: Ignoring invalid distribution ~atplotlib (C:\Users\Anushka\anaconda3\Lib\site-packages)

In [41]:
import spacy

nlp = spacy.load("en_core_web_sm")

text = "Anushka is learning Natural Language Processing in Pune."

doc = nlp(text)

for token in doc:
    print(token.text)

Anushka
is
learning
Natural
Language
Processing
in
Pune
.

# Stemming is a text preprocessing technique in Natural Language Processing (NLP) that reduces words to their root or stem by removing prefixes or suffixes.

In [42]:
from nltk.stem import PorterStemmer

ps = PorterStemmer()

words = ["playing", "played", "plays", "studies",
         "studying", "connected", "connection"]

for word in words:
    print(word, "->", ps.stem(word))

playing -> play
played -> play
plays -> play
studies -> studi
studying -> studi
connected -> connect
connection -> connect

# Lemmatization is a Natural Language Processing (NLP) technique that converts a word into its base dictionary form, called a lemma, using vocabulary and grammatical information.

In [44]:
from nltk.stem import WordNetLemmatizer

nltk.download('wordnet')
nltk.download('omw-1.4')

lemmatizer = WordNetLemmatizer()

words = ["playing", "studies", "cars", "children", "running"]

for word in words:
    print(word, "->", lemmatizer.lemmatize(word))

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\Anushka\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     C:\Users\Anushka\AppData\Roaming\nltk_data...

playing -> playing
studies -> study
cars -> car
children -> child
running -> running