In [1]:
pip install tensorflow

Requirement already satisfied: tensorflow in c:\users\anushka\anaconda3\lib\site-packages (2.21.0)
Requirement already satisfied: absl-py>=1.0.0 in c:\users\anushka\anaconda3\lib\site-packages (from tensorflow) (2.4.0)
Requirement already satisfied: astunparse>=1.6.0 in c:\users\anushka\anaconda3\lib\site-packages (from tensorflow) (1.6.3)
Requirement already satisfied: flatbuffers>=25.9.23 in c:\users\anushka\anaconda3\lib\site-packages (from tensorflow) (25.12.19)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in c:\users\anushka\anaconda3\lib\site-packages (from tensorflow) (0.7.0)
Requirement already satisfied: google_pasta>=0.1.1 in c:\users\anushka\anaconda3\lib\site-packages (from tensorflow) (0.2.0)
Requirement already satisfied: libclang>=13.0.0 in c:\users\anushka\anaconda3\lib\site-packages (from tensorflow) (18.1.1)
Requirement already satisfied: opt_einsum>=2.3.2 in c:\users\anushka\anaconda3\lib\site-packages (from tensorflow) (3.4.0)
Requirement already satisfied: packaging in c:\users\anushka\anaconda3\lib\site-packages (from tensorflow) (25.0)
Requirement already satisfied: protobuf<8.0.0,>=6.31.1 in c:\users\anushka\anaconda3\lib\site-packages (from tensorflow) (7.35.0)
Requirement already satisfied: requests<3,>=2.21.0 in c:\users\anushka\anaconda3\lib\site-packages (from tensorflow) (2.32.5)
Requirement already satisfied: setuptools in c:\users\anushka\anaconda3\lib\site-packages (from tensorflow) (80.9.0)
Requirement already satisfied: six>=1.12.0 in c:\users\anushka\anaconda3\lib\site-packages (from tensorflow) (1.17.0)
Requirement already satisfied: termcolor>=1.1.0 in c:\users\anushka\anaconda3\lib\site-packages (from tensorflow) (3.3.0)
Requirement already satisfied: typing_extensions>=3.6.6 in c:\users\anushka\anaconda3\lib\site-packages (from tensorflow) (4.15.0)
Requirement already satisfied: wrapt>=1.11.0 in c:\users\anushka\anaconda3\lib\site-packages (from tensorflow) (1.17.0)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in c:\users\anushka\anaconda3\lib\site-packages (from tensorflow) (1.80.0)
Requirement already satisfied: keras>=3.12.0 in c:\users\anushka\anaconda3\lib\site-packages (from tensorflow) (3.14.1)
Requirement already satisfied: numpy>=1.26.0 in c:\users\anushka\anaconda3\lib\site-packages (from tensorflow) (2.3.5)
Requirement already satisfied: h5py<3.15.0,>=3.11.0 in c:\users\anushka\anaconda3\lib\site-packages (from tensorflow) (3.14.0)
Requirement already satisfied: ml_dtypes<1.0.0,>=0.5.1 in c:\users\anushka\anaconda3\lib\site-packages (from tensorflow) (0.5.4)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\anushka\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\anushka\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\anushka\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\anushka\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (2026.1.4)
Requirement already satisfied: wheel<1.0,>=0.23.0 in c:\users\anushka\anaconda3\lib\site-packages (from astunparse>=1.6.0->tensorflow) (0.45.1)
Requirement already satisfied: rich in c:\users\anushka\anaconda3\lib\site-packages (from keras>=3.12.0->tensorflow) (14.2.0)
Requirement already satisfied: namex in c:\users\anushka\anaconda3\lib\site-packages (from keras>=3.12.0->tensorflow) (0.1.0)
Requirement already satisfied: optree in c:\users\anushka\anaconda3\lib\site-packages (from keras>=3.12.0->tensorflow) (0.19.1)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\anushka\anaconda3\lib\site-packages (from rich->keras>=3.12.0->tensorflow) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\anushka\anaconda3\lib\site-packages (from rich->keras>=3.12.0->tensorflow) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in c:\users\anushka\anaconda3\lib\site-packages (from markdown-it-py>=2.2.0->rich->keras>=3.12.0->tensorflow) (0.1.2)
Note: you may need to restart the kernel to use updated packages.

WARNING: Ignoring invalid distribution ~atplotlib (C:\Users\Anushka\anaconda3\Lib\site-packages)
WARNING: Ignoring invalid distribution ~atplotlib (C:\Users\Anushka\anaconda3\Lib\site-packages)
WARNING: Ignoring invalid distribution ~atplotlib (C:\Users\Anushka\anaconda3\Lib\site-packages)

In [3]:
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from sklearn.model_selection import train_test_split

In [4]:
df = pd.DataFrame({
    "soil_moisture": [0.10, 0.15, 0.20, 0.25, 0.40, 0.60, 0.35, 0.18,
                      0.45, 0.05, 0.80, 0.27, 0.55, 0.70, 0.12, 0.30],
    "temperature_c": [34, 30, 26, 22, 28, 30, 19, 22,
                      35, 24, 33, 33, 21, 25, 20, 29],
    "sunlight_hours": [9, 8, 7, 4, 8, 10, 3, 10,
                       12, 5, 9, 11, 2, 6, 1, 9],
    "needs_water": [1, 1, 1, 0, 0, 0, 0, 1,
                    0, 1, 0, 1, 0, 0, 1, 1]
})

In [5]:
df

    soil_moisture  temperature_c  sunlight_hours  needs_water
0            0.10             34               9            1
1            0.15             30               8            1
2            0.20             26               7            1
3            0.25             22               4            0
4            0.40             28               8            0
5            0.60             30              10            0
6            0.35             19               3            0
7            0.18             22              10            1
8            0.45             35              12            0
9            0.05             24               5            1
10           0.80             33               9            0
11           0.27             33              11            1
12           0.55             21               2            0
13           0.70             25               6            0
14           0.12             20               1            1
15           0.30             29               9            1

In [6]:
df.columns

Index(['soil_moisture', 'temperature_c', 'sunlight_hours', 'needs_water'], dtype='object')

In [7]:
X = df[['soil_moisture', 'temperature_c', 'sunlight_hours']]
y = df['needs_water']

In [8]:
X_min = X.min()
X_max = X.max()
X_scaled = (X - X_min) / (X_max - X_min + 1e-8)

In [9]:
X_scaled

    soil_moisture  temperature_c  sunlight_hours
0        0.066667         0.9375        0.727273
1        0.133333         0.6875        0.636364
2        0.200000         0.4375        0.545455
3        0.266667         0.1875        0.272727
4        0.466667         0.5625        0.636364
5        0.733333         0.6875        0.818182
6        0.400000         0.0000        0.181818
7        0.173333         0.1875        0.818182
8        0.533333         1.0000        1.000000
9        0.000000         0.3125        0.363636
10       1.000000         0.8750        0.727273
11       0.293333         0.8750        0.909091
12       0.666667         0.1250        0.090909
13       0.866667         0.3750        0.454545
14       0.093333         0.0625        0.000000
15       0.333333         0.6250        0.727273

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42 , stratify = y)

In [11]:
model = keras.Sequential([
    layers.Input(shape= (X_train.shape[1],)),
    layers.Dense(8,activation= 'relu'),
    layers.Dense(1,activation = 'sigmoid')
])

In [12]:
model.compile(
    optimizer='sgd',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

In [13]:
X_train = np.asarray(X_train).astype('float32')
X_test = np.asarray(X_test).astype('float32')

y_train = np.asarray(y_train).astype('float32')
y_test = np.asarray(y_test).astype('float32')

In [14]:
history = model.fit(
    X_train,
    y_train,
    validation_data=(X_test, y_test),
    epochs=100,
    batch_size=4,
    verbose=1
)

Epoch 1/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 89ms/step - accuracy: 0.5000 - loss: 4.1201 - val_accuracy: 0.5000 - val_loss: 1.2714
Epoch 2/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.5000 - loss: 0.8762 - val_accuracy: 0.6667 - val_loss: 0.8021
Epoch 3/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.7000 - loss: 0.5770 - val_accuracy: 0.5000 - val_loss: 2.1145
Epoch 4/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.5000 - loss: 1.3097 - val_accuracy: 0.5000 - val_loss: 0.8817
Epoch 5/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.3000 - loss: 1.4881 - val_accuracy: 0.5000 - val_loss: 0.7303
Epoch 6/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.5000 - loss: 0.7053 - val_accuracy: 0.5000 - val_loss: 1.0553
Epoch 7/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.3000 - loss: 1.3399 - val_accuracy: 0.5000 - val_loss: 0.7168
Epoch 8/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.5000 - loss: 0.8124 - val_accuracy: 0.5000 - val_loss: 0.7476
Epoch 9/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.5000 - loss: 0.8152 - val_accuracy: 0.8333 - val_loss: 0.7260
Epoch 10/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.5000 - loss: 0.8222 - val_accuracy: 0.6667 - val_loss: 0.7204
Epoch 11/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.5000 - loss: 0.6830 - val_accuracy: 0.5000 - val_loss: 0.7438
Epoch 12/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.5000 - loss: 0.7677 - val_accuracy: 0.5000 - val_loss: 0.9570
Epoch 13/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.5000 - loss: 0.8553 - val_accuracy: 0.5000 - val_loss: 0.7243
Epoch 14/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.4000 - loss: 0.7595 - val_accuracy: 0.5000 - val_loss: 0.8856
Epoch 15/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.3000 - loss: 0.9505 - val_accuracy: 0.3333 - val_loss: 0.8405
Epoch 16/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.5000 - loss: 0.7869 - val_accuracy: 0.6667 - val_loss: 0.7315
Epoch 17/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.3000 - loss: 0.7644 - val_accuracy: 0.5000 - val_loss: 0.7412
Epoch 18/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.4000 - loss: 0.7336 - val_accuracy: 0.5000 - val_loss: 1.0119
Epoch 19/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.3000 - loss: 0.9044 - val_accuracy: 0.5000 - val_loss: 0.9895
Epoch 20/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.5000 - loss: 0.7812 - val_accuracy: 0.5000 - val_loss: 0.7487
Epoch 21/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.3000 - loss: 0.7434 - val_accuracy: 0.5000 - val_loss: 0.7617
Epoch 22/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.5000 - loss: 0.7352 - val_accuracy: 0.6667 - val_loss: 0.7362
Epoch 23/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.3000 - loss: 0.9031 - val_accuracy: 0.3333 - val_loss: 0.8245
Epoch 24/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.3000 - loss: 0.8927 - val_accuracy: 0.5000 - val_loss: 0.7392
Epoch 25/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.3000 - loss: 0.7435 - val_accuracy: 0.3333 - val_loss: 0.8002
Epoch 26/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.5000 - loss: 0.8237 - val_accuracy: 0.6667 - val_loss: 0.7404
Epoch 27/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.5000 - loss: 0.7199 - val_accuracy: 0.5000 - val_loss: 0.7566
Epoch 28/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.7000 - loss: 0.6695 - val_accuracy: 0.5000 - val_loss: 0.7591
Epoch 29/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.5000 - loss: 0.7276 - val_accuracy: 0.6667 - val_loss: 0.7467
Epoch 30/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.7000 - loss: 0.6659 - val_accuracy: 0.6667 - val_loss: 0.7493
Epoch 31/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.8000 - loss: 0.6653 - val_accuracy: 0.6667 - val_loss: 0.7467
Epoch 32/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.5000 - loss: 0.7221 - val_accuracy: 0.5000 - val_loss: 0.7721
Epoch 33/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.4000 - loss: 0.7831 - val_accuracy: 0.6667 - val_loss: 0.7467
Epoch 34/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.6000 - loss: 0.6642 - val_accuracy: 0.6667 - val_loss: 0.7533
Epoch 35/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.5000 - loss: 0.7434 - val_accuracy: 0.6667 - val_loss: 0.7470
Epoch 36/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.4000 - loss: 0.7262 - val_accuracy: 0.5000 - val_loss: 0.7801
Epoch 37/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.3000 - loss: 0.9196 - val_accuracy: 0.3333 - val_loss: 0.8073
Epoch 38/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.5000 - loss: 0.8106 - val_accuracy: 0.5000 - val_loss: 0.7794
Epoch 39/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.6000 - loss: 0.7771 - val_accuracy: 0.6667 - val_loss: 0.7514
Epoch 40/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.5000 - loss: 0.7085 - val_accuracy: 0.5000 - val_loss: 0.8171
Epoch 41/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.5000 - loss: 0.7250 - val_accuracy: 0.5000 - val_loss: 0.7619
Epoch 42/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.5000 - loss: 0.7213 - val_accuracy: 0.5000 - val_loss: 0.8293
Epoch 43/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.5000 - loss: 0.6857 - val_accuracy: 0.5000 - val_loss: 0.7777
Epoch 44/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.6000 - loss: 0.6782 - val_accuracy: 0.5000 - val_loss: 0.7590
Epoch 45/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.5000 - loss: 0.6896 - val_accuracy: 0.5000 - val_loss: 0.8219
Epoch 46/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.5000 - loss: 0.7077 - val_accuracy: 0.6667 - val_loss: 0.7626
Epoch 47/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.6000 - loss: 0.6849 - val_accuracy: 0.5000 - val_loss: 0.8355
Epoch 48/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.5000 - loss: 0.6804 - val_accuracy: 0.5000 - val_loss: 0.7730
Epoch 49/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.6000 - loss: 0.7129 - val_accuracy: 0.5000 - val_loss: 0.8304
Epoch 50/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.5000 - loss: 0.6956 - val_accuracy: 0.3333 - val_loss: 0.7750
Epoch 51/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.6000 - loss: 0.6787 - val_accuracy: 0.5000 - val_loss: 0.7634
Epoch 52/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.5000 - loss: 0.6933 - val_accuracy: 0.5000 - val_loss: 0.8312
Epoch 53/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.5000 - loss: 0.6744 - val_accuracy: 0.5000 - val_loss: 0.7755
Epoch 54/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.7000 - loss: 0.6558 - val_accuracy: 0.6667 - val_loss: 0.7703
Epoch 55/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.4000 - loss: 0.6756 - val_accuracy: 0.5000 - val_loss: 0.8058
Epoch 56/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.5000 - loss: 0.6862 - val_accuracy: 0.6667 - val_loss: 0.7754
Epoch 57/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.5000 - loss: 0.7025 - val_accuracy: 0.5000 - val_loss: 0.8145
Epoch 58/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.6000 - loss: 0.6647 - val_accuracy: 0.5000 - val_loss: 0.7800
Epoch 59/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.6000 - loss: 0.6928 - val_accuracy: 0.3333 - val_loss: 0.7880
Epoch 60/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.7000 - loss: 0.6532 - val_accuracy: 0.6667 - val_loss: 0.7782
Epoch 61/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.7000 - loss: 0.6527 - val_accuracy: 0.6667 - val_loss: 0.7807
Epoch 62/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.6000 - loss: 0.6757 - val_accuracy: 0.6667 - val_loss: 0.7763
Epoch 63/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.6000 - loss: 0.7008 - val_accuracy: 0.5000 - val_loss: 0.7759
Epoch 64/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.5000 - loss: 0.7798 - val_accuracy: 0.5000 - val_loss: 0.8127
Epoch 65/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.5000 - loss: 0.6900 - val_accuracy: 0.5000 - val_loss: 0.8320
Epoch 66/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.6000 - loss: 0.6694 - val_accuracy: 0.3333 - val_loss: 0.7904
Epoch 67/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.6000 - loss: 0.6755 - val_accuracy: 0.3333 - val_loss: 0.7903
Epoch 68/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.6000 - loss: 0.6794 - val_accuracy: 0.5000 - val_loss: 0.8409
Epoch 69/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.5000 - loss: 0.6683 - val_accuracy: 0.3333 - val_loss: 0.7893
Epoch 70/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.6000 - loss: 0.6805 - val_accuracy: 0.6667 - val_loss: 0.7770
Epoch 71/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.5000 - loss: 0.6966 - val_accuracy: 0.5000 - val_loss: 0.8020
Epoch 72/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.7000 - loss: 0.7101 - val_accuracy: 0.6667 - val_loss: 0.7822
Epoch 73/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.5000 - loss: 0.6828 - val_accuracy: 0.6667 - val_loss: 0.7806
Epoch 74/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.6000 - loss: 0.6489 - val_accuracy: 0.6667 - val_loss: 0.7862
Epoch 75/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.6000 - loss: 0.6510 - val_accuracy: 0.6667 - val_loss: 0.7864
Epoch 76/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.4000 - loss: 0.7764 - val_accuracy: 0.3333 - val_loss: 0.7899
Epoch 77/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.7000 - loss: 0.6470 - val_accuracy: 0.6667 - val_loss: 0.7861
Epoch 78/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.6000 - loss: 0.6781 - val_accuracy: 0.6667 - val_loss: 0.7807
Epoch 79/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.5000 - loss: 0.6844 - val_accuracy: 0.5000 - val_loss: 0.8241
Epoch 80/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.7000 - loss: 0.6816 - val_accuracy: 0.3333 - val_loss: 0.7957
Epoch 81/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.6000 - loss: 0.6695 - val_accuracy: 0.3333 - val_loss: 0.7895
Epoch 82/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.7000 - loss: 0.6471 - val_accuracy: 0.6667 - val_loss: 0.7860
Epoch 83/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.5000 - loss: 0.6724 - val_accuracy: 0.5000 - val_loss: 0.8241
Epoch 84/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.6000 - loss: 0.6540 - val_accuracy: 0.3333 - val_loss: 0.7978
Epoch 85/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.4000 - loss: 0.7469 - val_accuracy: 0.6667 - val_loss: 0.7845
Epoch 86/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.5000 - loss: 0.7212 - val_accuracy: 0.5000 - val_loss: 0.8408
Epoch 87/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.5000 - loss: 0.7156 - val_accuracy: 0.6667 - val_loss: 0.7843
Epoch 88/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.5000 - loss: 0.7238 - val_accuracy: 0.5000 - val_loss: 0.8165
Epoch 89/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.6000 - loss: 0.6711 - val_accuracy: 0.3333 - val_loss: 0.7971
Epoch 90/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.7000 - loss: 0.6462 - val_accuracy: 0.3333 - val_loss: 0.8026
Epoch 91/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.6000 - loss: 0.6796 - val_accuracy: 0.5000 - val_loss: 0.8390
Epoch 92/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.5000 - loss: 0.7261 - val_accuracy: 0.6667 - val_loss: 0.7833
Epoch 93/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.6000 - loss: 0.6797 - val_accuracy: 0.6667 - val_loss: 0.7906
Epoch 94/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.4000 - loss: 0.7662 - val_accuracy: 0.6667 - val_loss: 0.7848
Epoch 95/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.6000 - loss: 0.6777 - val_accuracy: 0.6667 - val_loss: 0.7890
Epoch 96/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.5000 - loss: 0.6801 - val_accuracy: 0.5000 - val_loss: 0.8134
Epoch 97/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.5000 - loss: 0.7240 - val_accuracy: 0.5000 - val_loss: 0.8213
Epoch 98/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.7000 - loss: 0.6740 - val_accuracy: 0.3333 - val_loss: 0.7960
Epoch 99/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.5000 - loss: 0.6696 - val_accuracy: 0.6667 - val_loss: 0.7899
Epoch 100/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.6000 - loss: 0.6538 - val_accuracy: 0.6667 - val_loss: 0.7908

In [15]:
from tensorflow.keras import optimizers

In [16]:
opt = optimizers.SGD(learning_rate = 0.01, momentum = 0.9)